[package]
name = "delay"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", default-features = false, features = ["macros","time"] }
tauri = { workspace = true, features = [] }
